=head1 NAME

Plack::Middleware::GoogleAnalytics -

=head1 SYNOPSIS

  use Plack::Middleware::GoogleAnalytics;

=head1 DESCRIPTION

Plack::Middleware::GoogleAnalytics is

=head1 AUTHOR

lapis25 E<lt>lapis25@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

